config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :skip => [:registrations]
  root 'pages#home'
  get "pages/acces" => "pages#acces"

  get "admin/dashboard" => "admin#dashboard"
  get "admin/admin_events" => "admin#admin_events"
  get "admin/admin_contacts" => "admin#admin_contacts"
  get "admin/admin_accomodations" => "admin#admin_accomodations"
  get "admin/admin_lists" => "admin#admin_lists"

  resources :evenements
  get 'evenements/new'
  get 'evenements/edit'
  get 'evenements/show'
  get 'evenements/index'

  resources :liste_de_mariages
  get 'liste_de_mariages/new'
  get 'liste_de_mariages/edit'
  get 'liste_de_mariages/index'

  resources :contacts
  get 'contacts/new'
  get 'contacts/edit'
  get 'contacts/index'

  resources :hebergements
  get 'hebergements/new'
  get 'hebergements/edit'
  get 'hebergements/show'
  get 'hebergements/index'

  resources :posts
  get 'posts/new'
  get 'posts/edit'
  get 'posts/show'
  get 'posts/index'
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_one_attached :avatar
end

app/models/evenement.rb
class Evenement < ApplicationRecord
end

app/models/hebergement.rb
class Hebergement < ApplicationRecord
end

app/models/liste_de_mariage.rb
class ListeDeMariage < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!
  def dashboard

  end
  def admin_events
    @evenements = Evenement.all
  end
  def admin_contacts
    @contacts = Contact.all
  end
  def admin_accomodations
    @hebergements = Hebergement.all
  end
  def admin_lists
    @liste_de_mariages = ListeDeMariage.all
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]
  def index
    @contacts = Contact.all
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.save
    if @contact.save
      redirect_to contacts_path
    else
      render 'new'
    end
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])
    if @contact.update(contact_params)
      redirect_to contacts_path
    else
      render 'edit'
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    redirect_to admin_admin_contacts_path
  end

  private
  def contact_params
    params.require(:contact).permit(:firstname, :lastname, :role, :phonenumber, :email, :avatar)
  end

end

app/controllers/evenements_controller.rb
class EvenementsController < ApplicationController
  before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]
  def index
    @evenements = Evenement.order(:date, :time)
  end

  def show
    @evenement = Evenement.find(params[:id])
  end

  def new
    @evenement = Evenement.new
  end

  def create
    @evenement = Evenement.new(evenement_params)
    @evenement.save
    if @evenement.save
      redirect_to @evenement
    else
      render 'new'
    end
  end

  def edit
    @evenement = Evenement.find(params[:id])
  end

  def update
    @evenement = Evenement.find(params[:id])
    if @evenement.update(evenement_params)
      redirect_to @evenement
    else
      render 'edit'
    end
  end

  def destroy
    @evenement = Evenement.find(params[:id])
    @evenement.destroy
    redirect_to admin_admin_events_path
  end

  private
  def evenement_params
    params.require(:evenement).permit(:title, :description, :adress, :city, :zipcode, :date, :time)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @hebergements = Hebergement.all
    @evenements = Evenement.order(:date, :time)
    @liste_de_mariages = ListeDeMariage.all
    @contacts = Contact.all
  end

  def acces
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.save
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_class?(test_path)
    return 'active' if request.path == test_path
    ''
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/evenements_helper.rb
module EvenementsHelper
end

app/helpers/hebergements_helper.rb
module HebergementsHelper
end

app/helpers/liste_de_mariages_helper.rb
module ListeDeMariagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/admin_accomodations.html.erb
<div class="admin-pannel page-wrapper">
  <div class="admin-page-container">
    <div class="admin-page-navigation">
      <%= render 'layouts/partials/admin_navbar' %>
    </div>
    <div class="admin-page-main">
      <h1 class="admin-title">Gérer les hébergements</h1>
      <% @hebergements.each do |hebergement| %>
      <div class="admin-card">
        <h3 class="admin-element-title"><%= hebergement.title %> </h3>
        <%= link_to 'Modifier', edit_hebergement_path(hebergement), :class => "card-button admin-button" %>
        <%= link_to 'Delete', hebergement_path(hebergement), method: :delete, data: {confirm: 'Es tu sûr(e) de vouloir effacer cet hébergement ?'}, :class => "card-button admin-button admin-danger"  %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/admin_contacts.html.erb
<div class="admin-pannel page-wrapper">
  <div class="admin-page-container">
    <div class="admin-page-navigation">
      <%= render 'layouts/partials/admin_navbar' %>
    </div>
    <div class="admin-page-main">
      <h1 class="admin-title">Gérer les contact</h1>
      <% @contacts.each do |contact| %>
      <div class="admin-card">
        <h3 class="admin-element-title"><%= contact.firstname %> <%= contact.lastname %></h3>
        <%= link_to 'Modifier', edit_contact_path(contact), :class => "card-button admin-button" %>
        <%= link_to 'Delete', contact_path(contact), method: :delete, data: {confirm: 'Es tu sûr(e) de vouloir effacer ce contact ?'}, :class => "card-button admin-button admin-danger"  %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/admin_events.html.erb
<div class="admin-pannel page-wrapper">
  <div class="admin-page-container">
    <div class="admin-page-navigation">
      <%= render 'layouts/partials/admin_navbar' %>
    </div>
    <div class="admin-page-main">
      <h1 class="admin-title">Gérer les évènements</h1>
      <% @evenements.each do |evenement| %>
      <div class="admin-card">
        <h3 class="admin-element-title"><%= evenement.title %> </h3>
        <%= link_to 'Modifier', edit_evenement_path(evenement), :class => "card-button admin-button" %>
        <%= link_to 'Delete', evenement_path(evenement), method: :delete, data: {confirm: 'Es tu sûr(e) de vouloir effacer cet évènement ?'}, :class => "card-button admin-button admin-danger"  %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/admin_lists.html.erb
<div class="admin-pannel page-wrapper">
  <div class="admin-page-container">
    <div class="admin-page-navigation">
      <%= render 'layouts/partials/admin_navbar' %>
    </div>
    <div class="admin-page-main">
      <h1 class="admin-title">Gérer les listes de mariage</h1>
      <% @liste_de_mariages.each do |liste| %>
      <div class="admin-card">
        <h3 class="admin-element-title"><%= liste.title %> </h3>
        <%= link_to 'Modifier', edit_liste_de_mariage_path(liste), :class => "card-button admin-button" %>
        <%= link_to 'Delete', liste_de_mariage_path(liste), method: :delete, data: {confirm: 'Es tu sûr(e) de vouloir effacer cette liste ?'}, :class => "card-button admin-button admin-danger"  %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/dashboard.html.erb
<div class="page-wrapper">
  <section id="admin-page">
    <h1 class="section-header">Admin Dashboard</h1>
    <%= render 'layouts/partials/admin_navbar' %>
  </section>
</div>

app/views/layouts/partials/_admin_navbar.html.erb
<div class="admin-navbar-wrapper">
  <h2 class="admin-title">Menu administrateur</h2>
  <h4>Programme</h4>
  <ul>
    <li><%= link_to 'Liste des évènements', admin_admin_events_path %></li>
    <li><%= link_to 'Nouvel évènement', new_evenement_path %></li>
  </ul>
  <h4>Hébergement</h4>
  <ul>
    <li><%= link_to 'Liste des hébergements', admin_admin_accomodations_path %></li>
    <li><%= link_to 'Nouvel hébergement', new_hebergement_path %></li>
  </ul>
  <h4>Contact</h4>
  <ul>
    <li><%= link_to 'Liste des contacts', admin_admin_contacts_path %></li>
    <li><%= link_to 'Nouveau contact', new_contact_path %></li>
  </ul>
  <h4>Liste de mariage</h4>
  <ul>
    <li><%= link_to 'Toutes les listes de mariage', admin_admin_lists_path %></li>
    <li><%= link_to 'Nouvelle liste de mariage', new_liste_de_mariage_path %></li>
  </ul>
</div>

app/views/layouts/partials/_footer.html.erb
<footer>
  <div class="footer-container">
    <p>Merci pour votre visite</p>
    <div class="footer-content">
      <div class="site-map">
        <h2>Plan du site</h2>
        <nav>
          <ul>
            <li><%= link_to 'Accueil', root_path, :class => current_class?(root_path) %></li>
            <li><%= link_to 'Accès', pages_acces_path, :class => current_class?(pages_acces_path) %></li>
            <li><%= link_to 'Hébergement', hebergements_path, :class => current_class?(hebergements_path) %></li>
            <li><%= link_to 'Programme', evenements_path, :class => current_class?(evenements_path) %></li>
            <li><%= link_to 'Liste de mariage', liste_de_mariages_path, :class => current_class?(liste_de_mariages_path) %></li>
            <li><%= link_to 'Contacts', contacts_path, :class => current_class?(contacts_path) %></li>
          </ul>
        </nav>
      </div>
      <div class="contact-info">
        <p>Contactez nous pour toute question</p>
        <%= link_to 'reception@mariage-camille-antoine.fr', "mailto:reception@mariage-camille-antoine.fr" %>
      </div>
      <div class="admin-acces">
        <%= link_to 'Accès administrateur', admin_admin_events_path %>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/partials/_main_navigation.html.erb
<div class="navbar-wrapper">
  <div class="navbar-container">
    <div class="navbar-logo">
        <h1><%= link_to root_path do %>Camille <span>&</span> Antoine<% end %></h1>
    </div>
    <div class="navbar-links">
      <nav>
        <ul>
          <li><%= link_to 'Accueil', root_path, :class => current_class?(root_path) %></li>
          <li><%= link_to 'Photos', 'http://picti.net/sgMwZ', :target => '_blank' %></li>
          <li><%= link_to 'Accès', pages_acces_path, :class => current_class?(pages_acces_path) %></li>
          <li><%= link_to 'Hébergement', hebergements_path, :class => current_class?(hebergements_path) %></li>
          <li><%= link_to 'Programme', evenements_path, :class => current_class?(evenements_path) %></li>
          <li><%= link_to 'Liste de mariage', liste_de_mariages_path, :class => current_class?(liste_de_mariages_path) %></li>
          <li><%= link_to 'Contacts', contacts_path, :class => current_class?(contacts_path) %></li>
        </ul>
      </nav>
    </div>
  </div>
</div>

<div class="mobile-navbar">
  <div class="mobile-navbar-logo">
      <h1><%= link_to root_path do %>Camille <span>&</span> Antoine<% end %></h1>
  </div>
  <div class="mobile-menu-icon">
    <button>Menu</button>
  </div>
</div>

<div class="mobile-menu">
  <div>
    <h1>Menu</h1>
    <nav>
      <ul>
        <li><%= link_to 'Accueil', root_path, :class => current_class?(root_path), :class => 'mobile-menu-link' %></li>
        <li><%= link_to 'Photos', 'http://picti.net/sgMwZ', :target => '_blank' %></li>
        <li><%= link_to 'Accès', pages_acces_path, :class => current_class?(pages_acces_path), :class => 'mobile-menu-link' %></li>
        <li><%= link_to 'Hébergement', hebergements_path, :class => current_class?(hebergements_path), :class => 'mobile-menu-link' %></li>
        <li><%= link_to 'Programme', evenements_path, :class => current_class?(evenements_path), :class => 'mobile-menu-link' %></li>
        <li><%= link_to 'Liste de mariage', liste_de_mariages_path, :class => current_class?(liste_de_mariages_path), :class => 'mobile-menu-link' %></li>
        <li><%= link_to 'Contacts', contacts_path, :class => current_class?(contacts_path), :class => 'mobile-menu-link' %></li>
      </ul>
    </nav>
  </div>
</div>