config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :skip => [:registrations]
  root 'pages#home'
  get "pages/acces" => "pages#acces"

  get "admin/dashboard" => "admin#dashboard"
  get "admin/admin_events" => "admin#admin_events"
  get "admin/admin_contacts" => "admin#admin_contacts"
  get "admin/admin_accomodations" => "admin#admin_accomodations"
  get "admin/admin_lists" => "admin#admin_lists"

  resources :evenements
  get 'evenements/new'
  get 'evenements/edit'
  get 'evenements/show'
  get 'evenements/index'

  resources :liste_de_mariages
  get 'liste_de_mariages/new'
  get 'liste_de_mariages/edit'
  get 'liste_de_mariages/index'

  resources :contacts
  get 'contacts/new'
  get 'contacts/edit'
  get 'contacts/index'

  resources :hebergements
  get 'hebergements/new'
  get 'hebergements/edit'
  get 'hebergements/show'
  get 'hebergements/index'

  resources :posts
  get 'posts/new'
  get 'posts/edit'
  get 'posts/show'
  get 'posts/index'
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_one_attached :avatar
end

app/models/evenement.rb
class Evenement < ApplicationRecord
end

app/models/hebergement.rb
class Hebergement < ApplicationRecord
end

app/models/liste_de_mariage.rb
class ListeDeMariage < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!
  def dashboard

  end
  def admin_events
    @evenements = Evenement.all
  end
  def admin_contacts
    @contacts = Contact.all
  end
  def admin_accomodations
    @hebergements = Hebergement.all
  end
  def admin_lists
    @liste_de_mariages = ListeDeMariage.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]
  def index
    @contacts = Contact.all
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.save
    if @contact.save
      redirect_to contacts_path
    else
      render 'new'
    end
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])
    if @contact.update(contact_params)
      redirect_to contacts_path
    else
      render 'edit'
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    redirect_to admin_admin_contacts_path
  end

  private
  def contact_params
    params.require(:contact).permit(:firstname, :lastname, :role, :phonenumber, :email, :avatar)
  end

end

app/controllers/evenements_controller.rb
class EvenementsController < ApplicationController
  before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]
  def index
    @evenements = Evenement.order(:date, :time)
  end

  def show
    @evenement = Evenement.find(params[:id])
  end

  def new
    @evenement = Evenement.new
  end

  def create
    @evenement = Evenement.new(evenement_params)
    @evenement.save
    if @evenement.save
      redirect_to @evenement
    else
      render 'new'
    end
  end

  def edit
    @evenement = Evenement.find(params[:id])
  end

  def update
    @evenement = Evenement.find(params[:id])
    if @evenement.update(evenement_params)
      redirect_to @evenement
    else
      render 'edit'
    end
  end

  def destroy
    @evenement = Evenement.find(params[:id])
    @evenement.destroy
    redirect_to admin_admin_events_path
  end

  private
  def evenement_params
    params.require(:evenement).permit(:title, :description, :adress, :city, :zipcode, :date, :time)
  end

end

app/controllers/hebergements_controller.rb
class HebergementsController < ApplicationController
  before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]
  def index
    @hebergements = Hebergement.all
  end

  def show
    @hebergement = Hebergement.find(params[:id])
  end

  def new
    @hebergement = Hebergement.new
  end

  def create
    @hebergement = Hebergement.new(hebergement_params)
    @hebergement.save
    if @hebergement.save
      redirect_to @hebergement
    else
      render 'new'
    end
  end

  def edit
    @hebergement = Hebergement.find(params[:id])
  end

  def update
    @hebergement = Hebergement.find(params[:id])
    if @hebergement.update(hebergement_params)
      redirect_to @hebergement
    else
      render 'edit'
    end
  end

  def destroy
    @hebergement = Hebergement.find(params[:id])
    @hebergement.destroy
    redirect_to admin_admin_accomodations_path
  end

  private
  def hebergement_params
    params.require(:hebergement).permit(:title, :description, :adress, :city, :zipcode, :phonenumber, :email, :website)
  end

end

app/controllers/liste_de_mariages_controller.rb
class ListeDeMariagesController < ApplicationController
  before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]
  def index
    @liste_de_mariages = ListeDeMariage.all
  end

  def new
    @liste_de_mariage = ListeDeMariage.new
  end

  def create
    @liste_de_mariage = ListeDeMariage.new(liste_de_mariage_params)
    @liste_de_mariage.save
    if @liste_de_mariage.save
      redirect_to liste_de_mariages_path
    else
      render 'new'
    end
  end

  def edit
    @liste_de_mariage = ListeDeMariage.find(params[:id])
  end

  def update
    @liste_de_mariage = ListeDeMariage.find(params[:id])
    if @liste_de_mariage.update(liste_de_mariage_params)
      redirect_to liste_de_mariages_path
    else
      render 'edit'
    end
  end

  def destroy
    @liste_de_mariage = ListeDeMariage.find(params[:id])
    @liste_de_mariage.destroy
    redirect_to admin_admin_lists_path
  end

  private
  def liste_de_mariage_params
    params.require(:liste_de_mariage).permit(:title, :link, :description)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @hebergements = Hebergement.all
    @evenements = Evenement.order(:date, :time)
    @liste_de_mariages = ListeDeMariage.all
    @contacts = Contact.all
  end

  def acces
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.save
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_class?(test_path)
    return 'active' if request.path == test_path
    ''
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/evenements_helper.rb
module EvenementsHelper
end

app/helpers/hebergements_helper.rb
module HebergementsHelper
end

app/helpers/liste_de_mariages_helper.rb
module ListeDeMariagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/evenements/edit.html.erb
<div class="admin-pannel page-wrapper">
  <div class="admin-page-container">
    <div class="admin-page-navigation">
      <%= render 'layouts/partials/admin_navbar' %>
    </div>
    <div class="admin-page-main">
      <h1 class="admin-title">Modifier <%= @evenement.title %></h1>
      <%= render 'evenements/partials/event_form' %>
    </div>
  </div>
</div>

app/views/evenements/index.html.erb
<div class="page-wrapper">

  <section id="events-page">
    <h1 class="section-header">Programme</h1>
    <p class="section-header">Découvrez les grands évènements du week end</p>
    <% if @evenements.any? %>
    <div class="event-cards-container">
      <% @evenements.each do |evenement| %>
        <%= link_to evenement_path(evenement) do %>
        <div class="planning-card">
          <div class="planning-card-date">
            <time><%= evenement.date.strftime('%b %d') %></time>
            <time><%= evenement.time.strftime('%H:%M') %></time>
            <%= image_tag('calendar-icon.svg') %>
          </div>
          <div class="planning-card-info">
            <h2><%= evenement.title %></h2>
            <p class='event-adress'><%= evenement.adress %></p>
            <p class='event-city'><%= evenement.city %></p>
          </div>
        </div>
        <% end %>
      <% end %>
    </div>
    <% else %>
      <h4>Pas encore d'évènement pour le moment, ça arrive vite 😉</h4>
    <% end %>
  </section>

</div>

app/views/evenements/new.html.erb
<div class="admin-pannel page-wrapper">
  <div class="admin-page-container">
    <div class="admin-page-navigation">
      <%= render 'layouts/partials/admin_navbar' %>
    </div>
    <div class="admin-page-main">
      <h1 class="admin-title">Nouvel évènement</h1>
      <%= render 'evenements/partials/event_form' %>
    </div>
  </div>
</div>

app/views/evenements/partials/_event_form.html.erb
<%= form_for @evenement do |f| %>
  <div class="form-wrapper">
    <%= f.label :title, 'Titre *' %>
    <%= f.text_field :title, :required => true, placeholder: "Requis" %>

    <%= f.label :description, 'Description' %>
    <%= f.text_area :description, :required => false, placeholder: "Optionel" %>

    <%= f.label :adress, 'Adresse' %>
    <%= f.text_field :adress, :required => false, placeholder: "Optionel" %>

    <%= f.label :city, 'Ville *' %>
    <%= f.text_field :city, :required => true, placeholder: "Requis" %>

    <%= f.label :zipcode, 'Code Postal' %>
    <%= f.text_field :zipcode, :required => false, placeholder: "Optionel" %>

    <%= f.label :date, 'Date *' %>
    <%= f.date_field :date, :required => true %>

    <%= f.label :time, 'Horaire *' %>
    <%= f.time_field :time, :required => true %>

    <% if current_page?(action: 'new') %>
      <%= f.submit 'Ajouter' %>
    <% end %>
    <% if current_page?(action: 'edit') %>
      <%= f.submit 'Mettre à Jour' %>
      <%= link_to 'Effacer', @evenement, method: :delete, data: {confirm: 'Veux tu vraiment effacer cet évènement ?'} %>
    <% end %>
  </div>
<% end %>

app/views/evenements/show.html.erb
<div class="page-wrapper">

  <section id="event-show-page">
    <h1 class="section-header"><%= @evenement.title %></h1>
    <p class="event-location"><%= @evenement.adress %> <%= @evenement.zipcode %> <%= @evenement.city %></p>
    <p class="event-date">Le <%= @evenement.date.strftime('%A, %b %d') %> à <%= @evenement.time.strftime('%H:%M') %></p>
    <div class="event-body-container">
      <p><%= @evenement.description %></p>
    </div>
    <%= link_to 'Retour à la liste des évènements', evenements_path, :class => 'section-button button-dark' %>

    <% if admin_signed_in? %>
    <div class="show-admin-links">
      <%= link_to 'Modifier', edit_evenement_path(@evenement), :class => 'card-button admin-button' %>
    </div>
    <% end %>
  </section>

</div>

app/views/hebergements/edit.html.erb
<div class="admin-pannel page-wrapper">
  <div class="admin-page-container">
    <div class="admin-page-navigation">
      <%= render 'layouts/partials/admin_navbar' %>
    </div>
    <div class="admin-page-main">
      <h1 class="admin-title">Modifier <%= @hebergement.title %></h1>
      <%= render 'hebergements/partials/hebergement_form' %>
    </div>
  </div>
</div>

app/views/hebergements/index.html.erb
<div class="page-wrapper">

  <section id="accomodation-page">
    <h1 class="section-header">Hébergements</h1>
    <p class="section-intro">Retrouvez tous les hôtels et hébergements de la région</p>
    <% if @hebergements.any? %>
    <div class="accomodation-cards-container">
      <% @hebergements.each do |hebergement| %>
      <div class="accomodation-card">
        <h2 class="card-header"><%= hebergement.title %></h2>
        <p><%= hebergement.description %></p>
        <%= link_to 'Détails', hebergement_path(hebergement), :class => 'card-button' %>
      </div>
      <% end %>
    </div>
    <% else %>
      <h4>Pas encore d'hébergements pour le moment, ça arrive vite 😉</h4>
    <% end %>
  </section>

</div>

app/views/hebergements/new.html.erb
<div class="admin-pannel page-wrapper">
  <div class="admin-page-container">
    <div class="admin-page-navigation">
      <%= render 'layouts/partials/admin_navbar' %>
    </div>
    <div class="admin-page-main">
      <h1 class="admin-title">Nouvel hébergement</h1>
      <%= render 'hebergements/partials/hebergement_form' %>
    </div>
  </div>
</div>

app/views/hebergements/partials/_hebergement_form.html.erb
<%= form_for @hebergement do |f| %>
  <div class="form-wrapper">
    <%= f.label :title, 'Nom *' %><br>
    <%= f.text_field :title, :required => true, placeholder: "Requis" %><br>
    <br>

    <%= f.label :description, 'Description' %><br>
    <%= f.text_area :description, :required => false, placeholder: "Optionel" %><br>
    <br>

    <%= f.label :adress, 'Adresse *' %><br>
    <%= f.text_field :adress, :required => true, placeholder: "Requis" %><br>
    <br>

    <%= f.label :city, 'Ville *' %><br>
    <%= f.text_field :city, :required => true, placeholder: "Requis" %><br>
    <br>

    <%= f.label :zipcode, 'Code Postal *' %><br>
    <%= f.text_field :zipcode, :required => true, placeholder: "Requis" %><br>
    <br>

    <%= f.label :phonenumber, 'Numéro de téléphone *' %><br>
    <%= f.text_field :phonenumber, :required => true, placeholder: "Requis" %><br>
    <br>

    <%= f.label :email, 'Email' %><br>
    <%= f.text_field :email, :required => false, placeholder: "Optionel" %><br>
    <br>

    <%= f.label :website, 'Site Web' %><br>
    <%= f.text_field :website, :required => false, placeholder: "Optionel - https://siteweb.com" %><br>
    <br>

    <% if current_page?(action: 'new') %>
      <%= f.submit 'Ajouter' %>
    <% end %>
    <% if current_page?(action: 'edit') %>
      <%= f.submit 'Mettre à Jour' %>
      <%= link_to 'Effacer', @hebergement, method: :delete, data: {confirm: 'Veux tu vraiment effacer cet hébergement ?'} %>
    <% end %>
  </div>
<% end %>

app/views/hebergements/show.html.erb
<div class="page-wrapper">

  <section id="accomodation-show-page">
    <h1 class="section-header"><%= @hebergement.title %></h1>
    <p class="section-intro"><%= @hebergement.description %></p>
    <div class="accomodation-contact-info">
      <h4>Adresse</h4>
      <ul>
        <li><%= @hebergement.adress %></li>
        <li><%= @hebergement.zipcode %> <%= @hebergement.city %></li>
      </ul>
      <%= link_to "#{@hebergement.phonenumber}", "tel:#{@hebergement.phonenumber}", :class => 'page-button button-dark' %>
      <% if @hebergement.email? %>
        <%= mail_to "#{@hebergement.email}", "Envoyer un email", :class => 'page-button button-dark' %>
      <% end %>
      <% if @hebergement.website? %>
        <%= link_to "Site Web", "#{@hebergement.website}", target: "_blank", :class => 'page-button button-dark' %>
      <% end %>
    </div>
    <%= link_to "Retour aux autres hébergements", hebergements_path, :class => 'page-button button-dark' %>

    <% if admin_signed_in? %>
    <div class="show-admin-links">
      <%= link_to 'Modifier', edit_hebergement_path(@hebergement), :class => 'card-button admin-button' %>
    </div>
    <% end %>

  </section>

</div>

app/views/liste_de_mariages/edit.html.erb
<div class="admin-pannel page-wrapper">
  <div class="admin-page-container">
    <div class="admin-page-navigation">
      <%= render 'layouts/partials/admin_navbar' %>
    </div>
    <div class="admin-page-main">
      <h1 class="admin-title">Modifier <%= @liste_de_mariage.title %></h1>
      <%= render 'liste_de_mariages/partials/list_form' %>
    </div>
  </div>
</div>

app/views/liste_de_mariages/index.html.erb
<div class="page-wrapper">

  <section id="wedding-list-page">
    <h1 class="section-header">Liste de mariage</h1>
    <% if @liste_de_mariages.any? %>
    <% @liste_de_mariages.each do |liste| %>
      <% if liste.description? %>
        <p class="section-intro"><%= liste.description %></p>
      <% end %>
    <div class="list-cards-container">
        <%= link_to liste.link, target: "_blank", :class => 'list-card-link' do %>
          <div class="list-card">
            <div class="list-card-image">
              <%= image_tag('gift-icon.svg') %>
            </div>
            <div class="list-card-content">
              <h3><%= liste.title %></h3>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <% else %>
      <h4>Pas encore de liste pour le moment, ça arrive vite 😉</h4>
    <% end %>
  </section>

</div>

app/views/liste_de_mariages/new.html.erb
<div class="admin-pannel page-wrapper">
  <div class="admin-page-container">
    <div class="admin-page-navigation">
      <%= render 'layouts/partials/admin_navbar' %>
    </div>
    <div class="admin-page-main">
      <h1 class="admin-title">Nouvelle liste de mariage</h1>
      <%= render 'liste_de_mariages/partials/list_form' %>
    </div>
  </div>
</div>

app/views/liste_de_mariages/partials/_list_form.html.erb
<%= form_for @liste_de_mariage do |f| %>
  <div class="form-wrapper">
    <%= f.label :title, 'Nom *' %><br>
    <%= f.text_field :title, :required => true, placeholder: "Requis" %><br>
    <br>

    <%= f.label :link, 'Lien *' %><br>
    <%= f.text_field :link, :required => true, placeholder: "Requis - https://siteweb.com" %><br>
    <br>

    <%= f.label :description, 'Description' %><br>
    <%= f.text_area :description, :required => false, placeholder: "Optionel" %><br>
    <br>

    <% if current_page?(action: 'new') %>
      <%= f.submit 'Ajouter' %>
    <% end %>
    <% if current_page?(action: 'edit') %>
      <%= f.submit 'Mettre à Jour' %>
      <%= link_to 'Effacer', @liste_de_mariage, method: :delete, data: {confirm: 'Veux tu vraiment effacer ce lien ?'} %>
    <% end %>
  </div>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<div class="page-wrapper">

  <h1>Modfier <%= @post.title %></h1>
  <%= render 'posts/partials/post_form' %>

</div>

app/views/posts/index.html.erb
<div class="page-wrapper">
  
  <h1>Tous les posts</h1>

  <% if @posts.any? %>
    <ul>
    <% @posts.each do |post| %>
      <li><%= link_to post.title, post_path(post) %></li>
    <% end %>
    </ul>
  <% else %>
    <h4>Pas encore de posts pour le moment, ça arrive vite 😉</h4>
  <% end %>
  
</div>

app/views/posts/new.html.erb
<div class="page-wrapper">
  
<h1>Nouveau Post</h1>
<%= render 'posts/partials/post_form' %>

</div>

app/views/posts/partials/_post_form.html.erb
<%= form_for @post do |f| %>
  <div class="form-wrapper">
    <%= f.label :title, 'Titre *' %><br>
    <%= f.text_field :title, :required => true, placeholder: "Requis" %><br>
    <br>

    <%= f.label :body, 'Contenu *' %><br>
    <%= f.text_area :body, :required => true, placeholder: "Requis"%><br>
    <br>

    <% if current_page?(action: 'new') %>
      <%= f.submit 'Ajouter' %>
    <% end %>
    <% if current_page?(action: 'edit') %>
      <%= f.submit 'Mettre à Jour' %>
      <%= link_to 'Effacer', @post, method: :delete, data: {confirm: 'Veux tu vraiment effacer ce post ?'} %>
    <% end %>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="page-wrapper">

  <h1><%= @post.title %></h1>
  <p><%= @post.body %></p>
  
</div>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>